# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Will Johnson
email: will.johnson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Model the Learning
  
  
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://wj107.github.io" # the base hostname & protocol for your site

#sidebar
default-image: default.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer


# Build settings
markdown: kramdown
permalink: /:title/
paginate: 3
paginate_path: /page:num/

# Tracker
#analytics: UA-83979019-1

# Comments
#disqus: yes
#disqus-shortname: webjeda-demo

#social

twitter: http://twitter.com/@wjohnson107
github: http://github.com/wj107
email: will.johnson@gmail.com



# Sass style
sass:
  style: compressed

# Ruby Gems
#plugins: [jekyll-paginate, jekyll-seo-tag]

